# Generated by Django 6.0.5 on 2026-05-15 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255, verbose_name='razón social')),
                ('contact_name', models.CharField(blank=True, default='', max_length=150, verbose_name='nombre de contacto')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='correo de contacto')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='teléfono de contacto')),
                ('service_description', models.TextField(blank=True, default='', verbose_name='servicio que provee')),
                ('contract_start_date', models.DateField(verbose_name='inicio del contrato')),
                ('contract_end_date', models.DateField(verbose_name='fin del contrato')),
                ('renewal_notification_days', models.PositiveIntegerField(default=30, verbose_name='días antes para notificar')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='estado')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'suppliers',
                'ordering': ['business_name'],
            },
        ),
    ]
