# Generated by Django 6.0.5 on 2026-05-15 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nombre del servicio')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_start_date', models.DateField(verbose_name='inicio del contrato')),
                ('contract_end_date', models.DateField(verbose_name='fin del contrato')),
                ('renewal_notification_days', models.PositiveIntegerField(default=30, verbose_name='días antes para notificar')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notas')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='suppliers.supplier', verbose_name='proveedor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='suppliers.service', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'renovación',
                'verbose_name_plural': 'renovaciones',
                'db_table': 'renewals',
                'ordering': ['contract_end_date'],
            },
        ),
    ]
