# Generated by Django 6.0.5 on 2026-06-12 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("client", "Cliente"),
                            ("user", "Usuario"),
                            ("role", "Rol"),
                            ("web_type", "Tipo de Web"),
                            ("web_feature", "Característica"),
                            ("change_request", "Solicitud de Cambio"),
                            ("prospect", "Prospecto"),
                            ("payment", "Pago"),
                            ("system", "Sistema"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("entity_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Creación"),
                            ("update", "Actualización"),
                            ("delete", "Eliminación"),
                            ("login", "Inicio de sesión"),
                            ("logout", "Cierre de sesión"),
                            ("approve", "Aprobación"),
                            ("reject", "Rechazo"),
                            ("convert", "Conversión"),
                            ("export", "Exportación"),
                            ("other", "Otro"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría Global",
                "verbose_name_plural": "Auditorías Globales",
                "db_table": "global_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="global_audi_entity__c4eea5_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="global_audi_action_d42169_idx",
                    ),
                ],
            },
        ),
    ]
