# Generated by Django 6.0.5 on 2026-05-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('en_desarrollo', 'En desarrollo')], default='activo', max_length=20),
        ),
    ]
