# Generated by Django 6.0.5 on 2026-05-29 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('invoice', 'Factura'), ('receipt', 'Boleta'), ('credit_note', 'Nota de crédito'), ('debit_note', 'Nota de débito')], max_length=20)),
                ('document_number', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issue_date', models.DateField()),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('attachment', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'purchases',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(blank=True, default='', max_length=254)),
                ('document_type', models.CharField(choices=[('invoice', 'Factura'), ('receipt', 'Boleta'), ('credit_note', 'Nota de crédito'), ('debit_note', 'Nota de débito')], max_length=20)),
                ('document_number', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issue_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Anulado'), ('partial', 'Pago parcial')], default='pending', max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
