# Generated by Django 6.0.5 on 2026-05-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_colaborador_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='document_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
