# Generated by Django 6.0.5 on 2026-06-08 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_purchase_sale"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingEntryHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("purchase", "Compra"), ("sale", "Venta")],
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("creado", "Creado"),
                            ("editado", "Editado"),
                            ("cancelado", "Cancelado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_data", models.JSONField(blank=True, default=dict)),
                ("new_data", models.JSONField(blank=True, default=dict)),
                ("user_id", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "accounting_entry_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
