# Generated by Django 6.0.5 on 2026-05-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_plan_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
        ),
    ]
