# Generated by Django 6.0.5 on 2026-06-04 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_changerequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelTable(
            name="client",
            table="elomux_clients",
        ),
        migrations.CreateModel(
            name="ClientHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_state",
                    models.JSONField(
                        help_text="Instantánea del estado anterior a la mutación."
                    ),
                ),
                (
                    "new_state",
                    models.JSONField(
                        help_text="Instantánea del estado posterior a la mutación."
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_history_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_history",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "elomux_clients_history",
                "ordering": ["-changed_at"],
            },
        ),
    ]
