# Generated by Django 6.0.5 on 2026-05-15 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('renewal', 'Renovación'), ('expiration', 'Vencimiento')], max_length=20, verbose_name='tipo de alerta')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='leída')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='suppliers.supplier', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
