# Generated by Django 6.0.5 on 2026-05-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('suppliers', '0002_service_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='renewal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='suppliers.renewal', verbose_name='renovación'),
        ),
        migrations.AddField(
            model_name='alert',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='suppliers.service', verbose_name='servicio'),
        ),
    ]
