# Generated by Django 6.0.5 on 2026-05-15 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_renewal_alert_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20, verbose_name='canal')),
                ('status', models.CharField(choices=[('success', 'Éxito'), ('failed', 'Falló')], max_length=20, verbose_name='estado')),
                ('recipient', models.CharField(blank=True, default='', max_length=255, verbose_name='destinatario')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='mensaje de error')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado el')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='alerts.alert', verbose_name='alerta')),
            ],
            options={
                'verbose_name': 'historial de envío',
                'verbose_name_plural': 'historial de envíos',
                'db_table': 'alert_notification_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
